headersOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/benkennon/Projects_Archive/dawg/ai-dawg-deploy/.svelte-kit/netlify"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "microphone=(self), camera=(), geolocation=(), payment=()"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: blob:; font-src 'self' data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.anthropic.com https://api.deepgram.com; media-src 'self' blob: data:; worker-src 'self' blob:; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
for = "/_app/immutable/*"

[headers.values]
cache-control = "public, immutable, max-age=31536000"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "microphone=(self), camera=(), geolocation=(), payment=()"
Content-Security-Policy = "default-src 'self';\n      script-src 'self' 'unsafe-inline' 'unsafe-eval';\n      style-src 'self' 'unsafe-inline';\n      img-src 'self' data: https: blob:;\n      font-src 'self' data:;\n      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.anthropic.com https://api.deepgram.com;\n      media-src 'self' blob: data:;\n      worker-src 'self' blob:;\n      frame-ancestors 'none';\n      base-uri 'self';\n      form-action 'self';"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
for = "/build/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "*"
to = "/.netlify/functions/sveltekit-render"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]