packages:
  - 'web'
  - 'api'
  - 'deploy'
  - 'shared/*'
  - '*-engine'
  - 'control-plane'
  - 'frontend'
  - 'observatory'
  - 'agents'
  - 'desktop-app'
  - 'packages/*'
  - 'packages/daw-audio'
  - 'packages/daw-transport'
  - 'packages/shared-types'
