---
id: T-01JCKM7B2PMZK8V4N3WX6Q9R1T
title: "Real-time Audio Integration for Coaching Widgets"
created_at: 2025-10-03T03:35:00Z
updated_at: 2025-10-03T03:35:00Z
status: ready
priority: P2
owner: instance-2

rationale: |
  Enable live audio capture and analysis in coaching session. Currently PerformanceScorer
  and WaveformAnnotations are integrated but need real audio context to function.

scope:
  - Initialize Web Audio API in coaching overlay
  - Connect microphone stream to PerformanceScorer
  - Connect microphone stream to WaveformAnnotations
  - Add recording controls (start/stop/pause)
  - Save recorded sessions with metadata

out_of_scope:
  - Audio effects/processing during recording
  - Multi-track recording
  - Cloud storage of recordings

interfaces:
  rest:
    - POST /api/sessions/record/start
    - POST /api/sessions/record/stop
    - GET /api/sessions/:id
  events:
    produces:
      - session.recording.started
      - session.recording.stopped
      - session.saved
    consumes:
      - coaching.session.started

acceptance_criteria:
  - Microphone permission requested on coaching session start
  - PerformanceScorer shows live pitch data during recording
  - WaveformAnnotations generates real-time feedback
  - Recording can be saved with session metadata
  - Playback of recorded session works correctly

test_plan:
  unit:
    - AudioContext initialization
    - MediaStream handling
    - Recording state management
  integration:
    - Audio flow from mic to widgets
    - Recording save/load
  e2e:
    - User starts coaching, records vocals, sees live feedback, saves session

risk: medium
estimate: 2 days

dependencies:
  - PerformanceScorer (existing)
  - WaveformAnnotations (existing)
  - LiveCoachingPanel (existing)

technical_notes: |
  - Modify /app/journey/page.tsx to add audio state
  - Create useAudioSession hook for audio lifecycle
  - Store recordings in IndexedDB for offline access
  - Pass audio context via props to widgets
