---
id: T-STABILITY-B-AUDIO-TYPES
title: "[P0 Stability] Fix Audio/WebAudio Engine Type Errors"
created_at: 2025-10-02T22:40:00Z
updated_at: 2025-10-02T22:40:00Z
status: ready
priority: P0-Stability
owner: instance-2
type: fix

rationale: |
  Stability sprint gate: audio processing types must be correct.
  17 production audio/WebAudio errors blocking reliable audio engine.
  Critical for pitch detection, playback, effects processing.

scope:
  - Fix EffectsPanel.tsx EQ/effects parameter types (8 errors)
  - Fix usePitchDetection Float32Array ArrayBuffer type (1 error)
  - Fix usePlayback Blob | undefined handling (1 error)
  - Fix pitchDetection.ts null checks and Float32Array types (3 errors)
  - Fix melodyAnalyzer.ts module import path (1 error)
  - Fix widgetIntegration.ts exportToWAV missing export (1 error)
  - Fix VoiceInterface.tsx SpeechRecognition types (2 errors)

out_of_scope:
  - EffectsPanel.example.tsx (79 errors - Bucket D)
  - Audio engine refactoring
  - New audio effects

acceptance_criteria:
  - All 17 audio type errors resolved
  - npm run type-check passes for audio files
  - Audio playback works without console errors
  - Pitch detection returns valid Float32Array
  - Effects apply without type coercion
  - No 'any' types in audio processing code

test_plan:
  unit:
    - Test pitch detection with sample audio
    - Verify effects processing types
  integration:
    - Record audio, verify waveform displays
    - Apply EQ, verify parameters update
    - Test playback with different track types
  manual:
    - Record vocals, check pitch visualization
    - Apply reverb/delay/compression
    - Export audio file

dependencies:
  - T-STABILITY-D-SHARED-TYPES (audio event contracts)

estimate: 1 day

technical_notes: |
  Files to fix:
  - src/widgets/EffectsPanel/EffectsPanel.tsx (8 errors)
  - src/core/usePitchDetection.ts (1 error)
  - src/core/usePlayback.ts (1 error)
  - src/utils/pitchDetection.ts (3 errors)
  - src/utils/melodyAnalyzer.ts (1 error)
  - src/utils/widgetIntegration.ts (1 error)
  - src/voice/VoiceInterface.tsx (2 errors)

  Key issues:
  - Float32Array<ArrayBufferLike> vs Float32Array<ArrayBuffer>
  - Blob | undefined needs proper null check
  - Module path '@/core/usePitchDetection' resolution
  - exportToWAV not exported from exportAudio module
  - SpeechRecognition types need browser API declarations

  Strategy:
  1. Fix Float32Array types (critical for pitch detection)
  2. Add proper null checks for optional audio data
  3. Fix module imports
  4. Add browser API type declarations
